const $=id=>document.getElementById(id),music=$('music'),video=$('goals'),coverMusic=$('cover-music');
let entered=false;
function coverMusicState(){const playing=!coverMusic.paused;$('cover-music-toggle').textContent=playing?'Ⅱ Pausar UEFA':'♫ Activar música UEFA';$('cover-music-toggle').setAttribute('aria-pressed',String(playing))}
coverMusic.volume=.7;coverMusic.addEventListener('play',()=>{if(entered)coverMusic.pause();coverMusicState()});coverMusic.addEventListener('pause',coverMusicState);
coverMusic.play().catch(coverMusicState);
$('cover-music-toggle').addEventListener('click',()=>{if(entered)return;if(coverMusic.paused)coverMusic.play().catch(()=>toast('Toca otra vez para activar UEFA.'));else coverMusic.pause()});
let toastTimer;function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
function musicState(){const playing=!music.paused;$('music-toggle').setAttribute('aria-pressed',playing);$('music-toggle').setAttribute('aria-label',playing?'Pausar música':'Reproducir música');$('music-toggle').innerHTML=playing?'♫ <span>Música</span>':'♫ <span>Activar</span>'}
music.addEventListener('play',musicState);music.addEventListener('pause',musicState);
$('enter').addEventListener('click',()=>{entered=true;coverMusic.pause();coverMusic.currentTime=0;$('invitation').hidden=false;document.body.classList.remove('closed');music.volume=.7;music.play().catch(()=>toast('Toca Música para activar Bruno Mars.'));video.muted=true;video.play().catch(()=>toast('Toca el video para reproducir los goles.'));$('cover').classList.add('leaving');setTimeout(()=>{$('cover').hidden=true;$('music-toggle').focus({preventScroll:true})},850);window.scrollTo(0,0)},{once:true});
$('music-toggle').addEventListener('click',()=>{if(music.paused)music.play().catch(()=>toast('No se pudo iniciar la música. Inténtalo de nuevo.'));else music.pause()});
$('replay').addEventListener('click',()=>{video.currentTime=0;video.play().catch(()=>toast('Toca reproducir en el video.'))});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)document.body.classList.add('effects-off');
function effectState(){const on=!document.body.classList.contains('effects-off');$('effects-toggle').setAttribute('aria-pressed',on);$('effects-toggle').setAttribute('aria-label',on?'Desactivar animaciones':'Activar animaciones')};effectState();
$('effects-toggle').addEventListener('click',()=>{document.body.classList.toggle('effects-off');effectState()});
for(let i=0;i<26;i++){const s=document.createElement('i');s.textContent=i%3?'✦':'✧';s.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*100}%;font-size:${9+Math.random()*14}px;--time:${3+Math.random()*4}s;--delay:-${Math.random()*8}s`;$('effects').append(s)}
const target=new Date('2026-10-18T13:30:00-04:00').getTime();function countdown(){const n=Math.max(0,Math.floor((target-Date.now())/1000));const vals=[Math.floor(n/86400),Math.floor(n/3600)%24,Math.floor(n/60)%60,n%60];['days','hours','minutes','seconds'].forEach((id,i)=>$(id).textContent=String(vals[i]).padStart(2,'0'));if(!n)$('count-label').textContent='¡Llegó el momento de celebrar a Leonardo!'}countdown();setInterval(countdown,1000);
async function copy(t){if(navigator.clipboard&&window.isSecureContext){try{await navigator.clipboard.writeText(t);return true}catch{}}const el=document.createElement('textarea');el.value=t;el.style.cssText='position:fixed;opacity:0';document.body.append(el);el.select();const ok=document.execCommand('copy');el.remove();return ok}
$('copy-map').addEventListener('click',async()=>toast(await copy('https://maps.app.goo.gl/zxuYWwvPTepZos7j7')?'Ubicación copiada.':'Abre Google Maps para compartir la ubicación.'));
$('share').addEventListener('click',async()=>{if(['localhost','127.0.0.1'].includes(location.hostname)||location.protocol==='file:'){toast('Este botón compartirá el enlace cuando publiques la invitación.');return}const url=location.href.split('#')[0];if(navigator.share){try{await navigator.share({title:'Leonardo · 10 años',text:'¡Estás convocado! Celebremos juntos un golazo de 10 años ⚽',url})}catch(e){if(e.name!=='AbortError')toast(await copy(url)?'Enlace copiado.':'No se pudo compartir.')}}else toast(await copy(url)?'Enlace de invitación copiado.':'No se pudo copiar el enlace.')});
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{$('large-photo').src=b.dataset.photo;$('photo-dialog').showModal()}));$('close-photo').onclick=()=>$('photo-dialog').close();$('photo-dialog').addEventListener('click',e=>{if(e.target===$('photo-dialog'))$('photo-dialog').close()});
